name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: List Directory
      run: |
        ls -al
        pwd
    - name: Just run
      run: |
        pwd
        python src bubble 2 1
    - name: Test with unittest
      run: |
        pwd
        python -m unittest discover -v
